CC=gcc -Wall -g

reverse: reverse.c
	$(CC) reverse.c -o reverse.o

first-word: first-word.c
	$(CC) first-word.c -o first-word.o

endianness: endianness.c
	$(CC) endianness.c -o endianness.o

binary-search-tree: bst.c binary-search-tree.c
	$(CC) bst.c binary-search-tree.c -o binary-search-tree.o
