CC=gcc -Wall -g

complex: complex.c complex.h test_complex.c
	$(CC) complex.c test_complex.c -o complex.o

complex_set: complex.h complex_set.h complex_set.c
	$(CC) complex_set.c

wc: wc.c
	$(CC) wc.c -o wc.o

emigration: emigration.c
	$(CC) emigration.c -o emigration.o

callback: callback.c
	$(CC) callback.c -o callback.o
